### ISSUE TITLE
char *invoke(const char *str, int length)  length must be size_t

### ISSUE THREAD

**Issue by Vany** [fluencelabs/c-template#1]
subj

**Comment by mikevoronov** [comment]
Hi, thank you for the issue. But using unsigned integer is widely known as a bad practice even for length that couldn't be negative.

More info could be found in the `On Unsigned Integers` section of [Google C++ style guide](https://google.github.io/styleguide/cppguide.html#Integer_Types).

**Comment by Vany** [comment]
Sorry for inconvinience, but can we discuss it ?
All functions in libc (`malloc`, `strlen`, ...) used to `size_t`, why this happens?
And i found that i forced to explicitly convert type of length to `size_t` when i'm using it.
This means that even if we use `int` on our side it becomes `uint` when it is used.

**Comment by mikevoronov** [comment]
Hi! 

Yes, you are right, but there are some pros and cons in signed and unsigned usage here: 
- the main disadvantage of using signed integers here is that this variant is less convenient than unsigned. Because it needs to check for negative values and explicitly convert it to unsigned for some library functions. 
- the main con of unsigned is the fact that they are more error-prone.

As you know, STL also uses unsigned for lengths and sizes, but on this 2013 panel of some C++ experts such as Bjarne Stroustrup, Andrei Alexandrescu, Herb Sutter, Scott Meyers agreed that it was a mistake; see the discussions at [12:12-13:08](https://www.youtube.com/watch?v=Puio5dly9N8#t=12m12s), [42:40-45:26](https://www.youtube.com/watch?v=Puio5dly9N8#t=42m40s), and [1:02:50-1:03:15](https://www.youtube.com/watch?v=Puio5dly9N8#t=1h2m50s) (time codes taken from [here](https://github.com/ericniebler/stl2/issues/182#issuecomment-287683189)).

Scott Mayers has written an excellent [article](https://aristeia.com/Papers/C++ReportColumns/sep95.pdf) about using signed and unsigned in interfaces. He highlighted the same problem as this one.

Some other good thoughts could be taken from this [conversation](https://github.com/ericniebler/stl2/issues/182).

Because all of these, we decided to use signed integer here.

**Comment by Vany** [comment]
yes, seems problem is outside of just type choosing.
